#pragma once

#include <cassert>

#define SAFE_ASSERT(EXPRESSION) assert(EXPRESSION); if (!(EXPRESSION)) return;
#define SAFE_ASSERT_RETVAL(EXPRESSION, RETURN_VALUE) assert(EXPRESSION); if (!(EXPRESSION)) return RETURN_VALUE;
#define SAFE_ASSERT_CONTINUE(EXPRESSION) assert(EXPRESSION);
#define SAFE_ASSERT_ABORT(EXPRESSION) if (!(EXPRESSION)) abort();
#define UNSAFE_ASSERT(EXPRESSION) assert(EXPRESSION);
